# Generated by Django 6.0.2 on 2026-02-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_options_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accounts",
                to="companies.company",
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="user_profiles",
        ),
    ]
